version: "3"

services:
  postgres-user:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "15433:5432"
    networks:
      - interview-network
    volumes:
      - db-user-data:/var/lib/postgresql/data

  pgadmin-interview:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "joni.oliveira89@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - postgres-user
    networks:
      - interview-network

  interview-users:
    build:
      context: users-api/src/main/docker
      dockerfile: Dockerfile.jvm
    ports:
      - "8080:8080"
    depends_on:
      - postgres-user
    networks:
      - interview-network

networks:
  interview-network:
    driver: bridge

volumes:
  db-user-data:
    driver: local
